<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.0 on win32)" generated="20210114 17:29:17.556" rpa="false">
<suite id="s1" name="Test Case2" source="C:\Users\Anna_Poimenova\PycharmProjects\RobotProject\test\test_case2.robot">
<test id="s1-t1" name="Test">
<kw name="Search and check">
<arguments>
<arg>2</arg>
</arguments>
<kw name="Open App" library="ComPayments">
<msg timestamp="20210114 17:29:18.692" level="INFO">Could not connect to port 4723 on host 127.0.0.1</msg>
<msg timestamp="20210114 17:29:18.692" level="INFO">Could not get IP address for host: 127.0.0.1</msg>
<msg timestamp="20210114 17:29:20.716" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FAAF5B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20210114 17:29:22.724" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FA957C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20210114 17:29:24.750" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FAAF8B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20210114 17:29:26.763" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FAAFA00&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20210114 17:29:17.672" endtime="20210114 17:29:26.763"></status>
</kw>
<status status="FAIL" starttime="20210114 17:29:17.672" endtime="20210114 17:29:26.763"></status>
</kw>
<tags>
<tag>basic</tag>
</tags>
<status status="FAIL" starttime="20210114 17:29:17.672" endtime="20210114 17:29:26.764" critical="yes">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FAAFA00&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20210114 17:29:17.556" endtime="20210114 17:29:26.766"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">basic</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test Case2">Test Case2</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210114 17:29:20.716" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FAAF5B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20210114 17:29:22.724" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FA957C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20210114 17:29:24.750" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002069FAAF8B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
</errors>
</robot>
